server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "${DB_URL:jdbc:mysql://localhost:3306/identity_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signerKey: "${JWT_SIGNER_KEY}"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

outbound:
  identity:
    client-id: "${GOOGLE_CLIENT_ID}"
    client-secret: "${GOOGLE_CLIENT_SECRET}"
    redirect-url: "${OAUTH_REDIRECT_URL}"

app:
  services:
    profile: "${PROFILE_SERVICE_URL:http://localhost:8081/profile}"
