server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret1234
    config:
      server-logging-level: WARNING

logging:
  level:
    org.springframework.data.neo4j.cypher.unrecognized: ERROR
    org.neo4j.driver: WARN
app:
  services:
    file: http://localhost:8084
